export const GET_CATEGORIES= 'GET_CATEGORIES';
export const ADD_CATEGORY= 'ADD_CATEGORY';
export const DELETE_CATEGORIES= 'DELETE_CATEGORIES';
export const CATEGORIES_LOADING= 'CATEGORIES_LOADING';
